# sample code to make automated comment in PR using ghapi

name: ghapi
on: pull_request

permissions: # permissions are needed to write a comment
  contents: read
  issues: write
  pull-requests: write

jobs:
  ghapi:
    runs-on: ubuntu-latest
    steps:        
    - name: install dependencies
      run: pip install ghapi 

    - name: see payload # this step is for debugging purposes only, so you can see the payload.
      run: echo "PAYLOAD:\n${PAYLOAD}\n"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}
      
    - name: Make a comment
      shell: python
      run: |
        import os # this python code in general should be in a python file & the python file should be run here
        from ghapi.core import GhApi
        owner,repo = os.environ['REPO'].split('/')
        api = GhApi(owner=owner, repo=repo)
        api.issues.create_comment(os.environ['NUMBER'], "Hey! We'll get back to you soon.!")
      env:
        NUMBER: ${{ github.event.number }} 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
