# sample code to schedule a workflow every 15mins
# this file should be in workflow directory, probably in ('.github/workflows/sheduled.yml')

name: scheduled

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        shell: python
        run: |
          import random
          print(random.randint(0, 900000))
